import { StyleSheet } from "react-native";

export const colors = {
  navy: "#0B243B",
  dark: "#071D30",
  yellow: "#FFDA60",
  paleYellow: "#FFEB9E",
  blue: "#1178F7",
  lightBlue: "#4CA6FF",
  white: "#FFFFFF",
  ink: "#172333",
  muted: "#AAB9CA",
  red: "#FF575C",
  green: "#29CE79",
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.navy },
  unavailableScreen: { alignItems: "center", justifyContent: "center", gap: 20, paddingHorizontal: 24 },
  unavailableClose: {
    position: "absolute",
    left: 14,
    width: 44,
    height: 56,
    alignItems: "center",
    justifyContent: "center",
  },
  unavailableCloseText: { color: colors.white, fontSize: 43, lineHeight: 49, fontWeight: "300" },
  unavailableText: { color: colors.white, fontSize: 17, textAlign: "center" },
  unavailableRetry: { color: colors.lightBlue, fontSize: 17, fontWeight: "800" },
  header: {
    height: 104,
    backgroundColor: colors.yellow,
    justifyContent: "flex-end",
    alignItems: "center",
  },
  closeButton: {
    position: "absolute",
    left: 14,
    bottom: 0,
    width: 44,
    height: 56,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
  },
  closeText: { color: colors.ink, fontSize: 43, lineHeight: 49, fontWeight: "300" },
  moreButton: {
    position: "absolute",
    right: 14,
    bottom: 0,
    width: 44,
    height: 56,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
  },
  moreText: { color: colors.ink, fontSize: 33, lineHeight: 42, fontWeight: "700" },
  kindTabs: { height: 56, flexDirection: "row", alignItems: "flex-end" },
  kindTab: {
    width: 75,
    height: 56,
    alignItems: "center",
    justifyContent: "center",
    borderTopLeftRadius: 13,
    borderTopRightRadius: 13,
    gap: 0,
  },
  kindTabSelected: { backgroundColor: colors.navy },
  kindTabIdle: { backgroundColor: colors.paleYellow },
  kindTabText: { fontSize: 13, lineHeight: 19, fontWeight: "800" },
  content: { paddingHorizontal: 16, paddingTop: 24, flexGrow: 1 },
  dateRow: { height: 42, flexDirection: "row", alignItems: "center", gap: 7 },
  dateText: { color: colors.lightBlue, fontSize: 18, fontWeight: "800" },
  amountCard: {
    minHeight: 124,
    borderRadius: 9,
    backgroundColor: colors.dark,
    marginTop: 17,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 23,
    gap: 14,
    borderWidth: 1,
    borderColor: "transparent",
  },
  amountCardActive: { borderColor: colors.blue },
  amountTextBlock: { flex: 1, justifyContent: "center" },
  amountValueRow: { flexDirection: "row", alignItems: "baseline", gap: 12 },
  amountHistory: { color: colors.muted, fontSize: 17, lineHeight: 24 },
  amountValue: {
    color: colors.white,
    fontSize: 44,
    fontWeight: "500",
    fontVariant: ["tabular-nums"],
  },
  amountPlaceholder: { color: "#718399" },
  baht: { color: "#718399", fontSize: 26, fontWeight: "700" },
  optionCard: {
    minHeight: 76,
    borderRadius: 9,
    backgroundColor: colors.dark,
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 23,
    gap: 18,
  },
  optionText: { flex: 1, color: colors.lightBlue, fontSize: 19, lineHeight: 27, fontWeight: "700" },
  categoryIcon: { width: 30, height: 40, alignItems: "center", justifyContent: "center" },
  categoryDetails: { flex: 1, justifyContent: "center" },
  categoryName: { color: colors.white, fontSize: 19, lineHeight: 25, fontWeight: "700" },
  categoryPlaceholder: { color: colors.lightBlue },
  categoryTags: { color: colors.muted, fontSize: 16, lineHeight: 22 },
  noteCard: {
    minHeight: 80,
    borderRadius: 9,
    backgroundColor: colors.dark,
    marginTop: 9,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 23,
    gap: 18,
  },
  focusedCard: { borderWidth: 1, borderColor: colors.blue, paddingHorizontal: 22 },
  noteInput: {
    flex: 1,
    height: 62,
    color: colors.white,
    fontSize: 19,
    lineHeight: 27,
    fontWeight: "700",
    paddingVertical: 0,
    outlineStyle: "solid",
    outlineColor: "transparent",
    outlineWidth: 0,
  },
  extraCard: {
    minHeight: 108,
    borderRadius: 9,
    backgroundColor: colors.dark,
    marginTop: 24,
    paddingTop: 16,
    paddingHorizontal: 17,
  },
  slipCardWrap: { marginTop: 24 },
  extraHeading: { color: colors.white, fontSize: 17, fontWeight: "700" },
  repeatRow: { minHeight: 69, flexDirection: "row", alignItems: "center", gap: 14, paddingLeft: 6 },
  transferHint: {
    color: colors.muted,
    fontSize: 15,
    lineHeight: 23,
    textAlign: "center",
    marginTop: 30,
    paddingHorizontal: 24,
  },
  saveButton: {
    position: "absolute",
    alignSelf: "center",
    width: 150,
    minHeight: 44,
    backgroundColor: colors.blue,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  saveText: { color: colors.white, fontSize: 20, fontWeight: "800" },
  error: {
    position: "absolute",
    left: 20,
    right: 20,
    color: "#FFB0B3",
    textAlign: "center",
    fontSize: 13,
    zIndex: 3,
  },
  menuDismiss: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, zIndex: 4 },
  menuCard: {
    position: "absolute",
    right: 0,
    top: 104,
    width: 218,
    minHeight: 52,
    backgroundColor: "#FFFBFF",
    borderColor: "#D9DDE5",
    borderWidth: 1,
    borderTopLeftRadius: 14,
    borderBottomLeftRadius: 14,
    borderBottomRightRadius: 14,
    zIndex: 5,
    elevation: 8,
    shadowColor: "#000000",
    shadowOpacity: 0.14,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 3 },
  },
  menuDelete: {
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    paddingHorizontal: 18,
  },
  menuDeleteText: { color: "#E84B55", fontSize: 17, fontWeight: "800" },
  exitOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, .64)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  exitCard: {
    width: "100%",
    maxWidth: 440,
    borderRadius: 16,
    backgroundColor: "#1E3A51",
    overflow: "hidden",
  },
  exitHero: { height: 112, backgroundColor: colors.yellow, alignItems: "center" },
  exitClose: {
    position: "absolute",
    top: 7,
    right: 8,
    width: 40,
    height: 40,
    zIndex: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  exitCloseText: { color: colors.ink, fontSize: 37, lineHeight: 40, fontWeight: "300" },
  exitPig: { position: "absolute", width: 200, height: 178, top: 20, alignSelf: "center" },
  exitBody: { alignItems: "center", paddingHorizontal: 13, paddingTop: 73, paddingBottom: 22 },
  exitTitle: {
    color: colors.white,
    fontSize: 21,
    lineHeight: 29,
    fontWeight: "800",
    textAlign: "center",
  },
  exitDescription: {
    color: colors.muted,
    fontSize: 16,
    lineHeight: 24,
    marginTop: 7,
    textAlign: "center",
  },
  exitActions: { flexDirection: "row", gap: 12, width: "100%", marginTop: 29 },
  exitSecondary: {
    flex: 1,
    height: 42,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.lightBlue,
    justifyContent: "center",
    alignItems: "center",
  },
  exitSecondaryText: { color: colors.lightBlue, fontSize: 17, fontWeight: "800" },
  exitPrimary: {
    flex: 1,
    height: 42,
    borderRadius: 22,
    backgroundColor: colors.blue,
    justifyContent: "center",
    alignItems: "center",
  },
  exitPrimaryText: { color: colors.white, fontSize: 17, fontWeight: "800" },
  disabled: { opacity: 0.5 },
  modalCenter: { flex: 1, justifyContent: "center", alignItems: "center" },
  modalShade: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: "rgba(0,0,0,.58)",
  },
  calendarCard: {
    width: "88%",
    maxWidth: 420,
    backgroundColor: colors.white,
    borderRadius: 18,
    padding: 18,
  },
  calendarTitle: { color: colors.ink, fontSize: 20, fontWeight: "800", textAlign: "center" },
  calendarMonthRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
  },
  calendarArrow: { width: 40, height: 40, alignItems: "center", justifyContent: "center" },
  calendarArrowText: { color: colors.blue, fontSize: 36, lineHeight: 40 },
  calendarMonth: { color: colors.ink, fontSize: 17, fontWeight: "700" },
  calendarGrid: { flexDirection: "row", flexWrap: "wrap" },
  calendarWeekday: {
    width: "14.285%",
    textAlign: "center",
    color: "#77899A",
    fontSize: 12,
    paddingVertical: 8,
  },
  calendarDay: {
    width: "14.285%",
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
  },
  calendarDayText: { color: colors.ink, fontSize: 15 },
  calendarSelected: { backgroundColor: colors.blue },
  calendarSelectedText: { color: colors.white, fontWeight: "800" },
  calendarActions: { flexDirection: "row", gap: 10, paddingTop: 16 },
  secondaryAction: {
    flex: 1,
    minHeight: 44,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.blue,
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryActionText: { color: colors.blue, fontSize: 16, fontWeight: "800" },
  primaryAction: {
    flex: 1,
    minHeight: 44,
    borderRadius: 24,
    backgroundColor: colors.blue,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryActionText: { color: colors.white, fontSize: 16, fontWeight: "800" },
});
